#!/bin/bash

IP=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
ARCH=$(/usr/bin/dpkg --print-architecture)

echo -e "\E[1;32m-> System Initialization creepContainer ($ARCH) ($IP)"
echo " "

if [[ -v FRONTAIL ]]; then
	echo -e "\E[1;32m=> Starting frontail – streaming logs to the browser"
	if [ -f /config/frontail.json ] ; then
		/usr/bin/frontail -d -h 0.0.0.0 -p 9002 --ui-highlight --ui-highlight-preset /config/frontail.conf -t dark --ui-hide-topbar --ui-no-indent -l 2000 -n 60 /logs/creepMiner.log
	else
		/usr/bin/frontail -d -h 0.0.0.0 -p 9002 --ui-highlight --ui-highlight-preset /etc/frontail.json -t dark --ui-hide-topbar --ui-no-indent -l 2000 -n 60 /logs/creepMiner.log
	fi
fi

if [[ -v C_SCRIPT ]]; then
	echo -e "\E[1;32m=> Custom script found"
	if [ -n "${C_SCRIPT}" ]; then
		echo "=> Executing ${C_SCRIPT}"
		chmod 755 /config/${C_SCRIPT} && /config/${C_SCRIPT}
	else
		echo " "
		echo -e "\E[1;31m      Warning : C_SCRIPT is set but not to script name specified"
		echo -e "\E[1;31m                E.G. /config/script.sh and set \E[1;36mC_SCRIPT=script.sh"
		echo " "
  	fi
fi

if [[ -v WEBPROC ]]; then
	echo -e "\E[1;32m=> Starting webproc - TBD"
	echo " "
	/usr/bin/webproc /etc/webproc.toml
else
	echo -e "\E[1;32m=> Starting Supervisor - the Process Control System"
	echo " "
	/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
fi
