version: '3'

services:
  miner:
    container_name: miner
    build: .
    ports:
      - 8124:8124
      - 9001:9001
      - 9002:9002
      - 9003:9003
    volumes:
      - /Volumes/wahu/creepMiner:/config
      - /Volumes/wahu/plots:/plots
      - /Volumes/wahu/creepMiner/logs:/logs      
    environment:
      - AUTO_START=TRUE
      - FRONTAIL=TRUE
      - C_SCRIPT=test.sh
#    restart: always